### ISSUE TITLE
Add ability to pass a list of pipeline properties

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-devsecops-alm#372]
### Description

There is a common pattern where consumers add more pipeline properties specific to their app.

This currently requires to write custom code using ibm_cd_tekton_pipeline_property . It would be desirable to have the ALM DA do this out of the box - with a list of properties passed as input of ci and cd pipelines.

**Comment by huayuenh** [comment]
This is now supported with the following input :
`ci_pipeline_properties`
`cd_pipeline_properties`
`cc_pipeline_properties`

The input expects a JSON 

example `
[
  {
    "pipeline_id": "ci",
    "properties": [
      {
        "name": "custom-param1",
        "type": "text",
        "value": "example1"
      },
      {
        "name": "custom-param2",
        "type": "secure",
        "value": "{vault::sm-compliance-secrets.Default.ibmcloud-api-key}"
      },
      {
        "name": "custom-param3",
        "type": "single_select",
        "value": "0",
        "enum": "[0,1,2]"
      }
    ]
  }
]
`
