### ISSUE TITLE
Enable referencing an existing github repository for the app code

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-devsecops-alm#389]

**Comment by padraic-edwards** [comment]
Works via setting 4 variables at the moment at the moment. We are enhancing the ALM to make it a simpler experience.

**Comment by huayuenh** [comment]
In the existing implementation, the following variables in the ALM need to be set to change from the sample app to a custom app

ci_app_repo_existing_git_id = "github"
ci_app_repo_existing_git_provider = "githubconsolidated"
ci_app_repo_existing_branch = "main"
ci_app_repo_existing_url  = "https://github.com/source-repo-owner/source-repo"
ci_app_repo_git_token_secret_name = <name of the secret in Secrets Manager containing the Git Token>
ci_app_group = <github-user-id>

A simplified approach is coming
