### ISSUE TITLE
Automatically add the CD service in the toolchain resource group

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-devsecops-alm#393]
### Description

This is currently done by calling 
```
# create CD service for toolchain use if variable is set
resource "ibm_resource_instance" "cd_instance" {
  count             = var.create_continuous_delivery_service_instance ? 1 : 0
  name              = "${var.prefix}-cd-instance"
  service           = "continuous-delivery"
  plan              = "professional"
  location          = var.toolchain_region
  resource_group_id = data.ibm_resource_group.toolchain_resource_group_id.id
}
```

If this is already available one of the many variable - suggest to enable by default.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by padraic-edwards** [comment]
We are planning to make the https://github.com/terraform-ibm-modules/terraform-ibm-devsecops-infrastructure module available in the community registry. This module creates a CD instance and every other pre-req for the ALM DA.

**Comment by huayuenh** [comment]
This is available in the latest release now.

See `

variable "create_cd_instance" {
  type        = bool
  description = "Set to `true` to create Continuous Delivery Service."
  default     = false
}

variable "cd_instance_name" {
  type        = string
  description = "The name of the CD instance."
  default     = "cd-devsecops"
}

variable "cd_service_plan" {
  type        = string
  description = "The Continuous Delivery service plan. Can be `lite` or `professional`."
  default     = "professional"
}`
