### ISSUE TITLE
Give ability to specific a prefix for all resource names

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-devsecops-alm#398]
### Description

Some resource can have a prefix, but some other are missing:
- ci_code_engine_project (must be unique per account)
- cd_code_engine_project (must be unique per account)
- registry_namespace (suggest to also give the possibility to append a randomly generated suffix as the namespace must be globally unique - this is a common pattern for names that must be globally unique - see https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/4146d0992bab7d920f4e66db48c7c7b804f5a95a/variables.tf#L121 for cos bucket names)

This is resulting in the need to ask users of the stack to input different names for each execution of the stack in same account. A prefix is also passed as input of the stack, so ideally, we should be able to pass that prefix for the resource above, reducing the need for the user to input full names for every run.

**Comment by vburckhardt** [comment]
This is complete - is there anything else to track here or should this be closed? @huayuenh

**Comment by huayuenh** [comment]
> This is complete - is there anything else to track here or should this be closed? @huayuenh

Fine to close. Thanks
