### ISSUE TITLE
Target secret group when creating new secrets

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/terraform-ibm-devsecops-alm#454]
### Description

When `create_signing_key = true` the signing key secret is created in the secret group specified in `sm_secret_group` even though there is a parameter `ci_sm_secret_group`. I would expect the latter value (if supplied) to be used when creating a new secret group for CI secrets like signing key. The same should apply to other secrets.
It's not quite clear however, how the logic should work when `create_secret_group = true` - as it is, it might imply that for any new secret created, its secret group should be created too.

I am considering the scenario where the credential secrets (apikeys) are provisioned centrally outside of the ALM DA but other things like signing keys may be managed by the ALM DA. In that case the deployer permissions may be different for different secrets groups (i.e. apikeys secrets group is read-only, while signing_keys secrets group may allow creating new secrets).

### New or affected modules

prereq/main.tf

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by huayuenh** [comment]
This secrets provisioning is really intended for use in a stack where we would create the Secrets Manager instance and the secrets in the same secret group or just create the secrets in the same group. Can consider the additional granularity later. For pre-provisioned secrets you can still specific a different secret group. For example the apikey used to run the pipelines, you can specify both the secret name and secret group for it. It is still limited to using the same Secrets Manager instance

`ci_pipeline_ibmcloud_api_key_secret_name` and `ci_pipeline_ibmcloud_api_key_secret_group`

**Comment by padraic-edwards** [comment]
No plans to add additional secret support at this time.
